### ISSUE TITLE
Could not locate a supported Microsoft Visual C++ installation

### ISSUE THREAD

**Issue by kenmaxnejp** [sicxu/Deep3DFaceRecon_pytorch#123]
Hi all,
I have already installed Microsoft Visual C++ 2015-2022 Redistributable(x64) 14.34.31931, but it keeps telling me that could not locate a supported Microsoft Visual C++ installation, what should I do?

(deep3d_pytorch) C:\Users\kenmax\Deep3DFaceRecon_pytorch>python test.py --name=test_model --epoch=20 --img_folder=./datasets/examples
C:\Users\kenmax\anaconda3\envs\deep3d_pytorch\lib\site-packages\kornia\augmentation\augmentation.py:1875: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
C:\Users\kenmax\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
----------------- Options ---------------
                add_image: True
               bfm_folder: BFM
                bfm_model: BFM_model_front.mat
                 camera_d: 10.0
                   center: 112.0
          checkpoints_dir: ./checkpoints
             dataset_mode: None
                 ddp_port: 12355
        display_per_batch: True
                    epoch: 20                                   [default: latest]
          eval_batch_nums: inf
                    focal: 1015.0
                  gpu_ids: 0
               img_folder: ./datasets/examples                  [default: examples]
                init_path: checkpoints/init_model/resnet50-0676ba61.pth
                  isTrain: False                                [default: None]
                    model: facerecon
                     name: test_model                           [default: face_recon]
                net_recon: resnet50
                    phase: test
                   suffix:
                  use_ddp: False                                [default: True]
              use_last_fc: False
               use_opengl: True
                  verbose: False
           vis_batch_nums: 1
               world_size: 1
                    z_far: 15.0
                   z_near: 5.0
----------------- End -------------------
C:\Users\kenmax\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\cuda\__init__.py:125: UserWarning:
NVIDIA GeForce RTX 4090 with CUDA capability sm_89 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 4090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
model [FaceReconModel] was created
loading the model from ./checkpoints\test_model\epoch_20.pth
0 ./datasets/examples\000002.jpg
Traceback (most recent call last):
  File "test.py", line 73, in <module>
    main(0, opt,opt.img_folder)
  File "test.py", line 63, in main
    model.test()           # run inference
  File "C:\Users\kenmax\Deep3DFaceRecon_pytorch\models\base_model.py", line 162, in test
    self.forward()
  File "C:\Users\kenmax\Deep3DFaceRecon_pytorch\models\facerecon_model.py", line 140, in forward
    self.pred_vertex, self.facemodel.face_buf, feat=self.pred_color)
  File "C:\Users\kenmax\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\kenmax\Deep3DFaceRecon_pytorch\util\nvdiffrast.py", line 61, in forward
    self.ctx = dr.RasterizeGLContext(device=device)
  File "C:\Users\kenmax\anaconda3\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "C:\Users\kenmax\anaconda3\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\ops.py", line 43, in _get_plugin
    raise RuntimeError("Could not locate a supported Microsoft Visual C++ installation")
RuntimeError: Could not locate a supported Microsoft Visual C++ installation

**Comment by duan123ty** [comment]
Well, I think you can change the "dr.RasterizeGLContext（device=device）" into "dr.RasterizeCudaContext（device=device）"。

**Comment by duan123ty** [comment]
By the way, RTX 4090 arch is higher than its basic requirement . Commend to view: 
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_capability())
If higher
solve

**Comment by xioaxiaomu** [comment]
Has this problem been resolved? What was the solution?

**Comment by JonnPDF** [comment]
If you have microsoft visual studio installer enter it and select (Modify) option on the visual studio that you have. Make sure that you installed the C++ package for desktop development because the file that the library tries to access exists there.
![image](https://github.com/user-attachments/assets/b8ca93b4-8042-43ec-bf15-99415c6f69f0)
![image](https://github.com/user-attachments/assets/ea17daab-d465-4d12-b538-b2a28b3bb4b1)
