### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by HWHHWHNO1** [sicxu/Deep3DFaceRecon_pytorch#156]
Traceback (most recent call last):
  File "test.py", line 76, in <module>
    main(0, opt,opt.img_folder)
  File "test.py", line 66, in main
    model.test()           # run inference
  File "/root/HWH/Vico2023/Deep3DFaceRecon_pytorch/models/base_model.py", line 162, in test
    self.forward()
  File "/root/HWH/Vico2023/Deep3DFaceRecon_pytorch/models/facerecon_model.py", line 135, in forward
    output_coeff = self.net_recon(self.input_img)
  File "/root/anaconda3/envs/deep3d_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/HWH/Vico2023/Deep3DFaceRecon_pytorch/models/networks.py", line 98, in forward
    x = self.backbone(x)
  File "/root/anaconda3/envs/deep3d_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/HWH/Vico2023/Deep3DFaceRecon_pytorch/models/networks.py", line 375, in forward
    return self._forward_impl(x)
  File "/root/HWH/Vico2023/Deep3DFaceRecon_pytorch/models/networks.py", line 360, in _forward_impl
    x = self.relu(x)
  File "/root/anaconda3/envs/deep3d_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/deep3d_pytorch/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 102, in forward
    return F.relu(input, inplace=self.inplace)
  File "/root/anaconda3/envs/deep3d_pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1117, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device

my CUDA version: 12.0
I have try different verion of pytorch, but this error still
I don't know how to solve

**Comment by 1264089591** [comment]
Same issue.

**Comment by johnren-code** [comment]
Have you solved it?
