### ISSUE TITLE
False error in training

### ISSUE THREAD

**Issue by gjxwwww8888** [sicxu/Deep3DFaceRecon_pytorch#167]
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    main(0, world_size, train_opt)
  File "train.py", line 87, in main
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/data1/data_gjx/train/face/Deep3DFaceRecon_pytorch/models/facerecon_model.py", line 185, in optimize_parameters
    self.compute_losses()
  File "/data1/data_gjx/train/face/Deep3DFaceRecon_pytorch/models/facerecon_model.py", line 155, in compute_losses
    pred_feat = self.net_recog(self.pred_face, trans_m)
  File "/data/data_gjx/anaconda3/envs/face/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data1/data_gjx/train/face/Deep3DFaceRecon_pytorch/models/networks.py", line 122, in forward
    image = self.preprocess(resize_n_crop(image, M, self.input_size))
  File "/data1/data_gjx/train/face/Deep3DFaceRecon_pytorch/models/networks.py", line 24, in resize_n_crop
    return warp_affine(image, M, dsize=(dsize, dsize))
  File "/data/data_gjx/anaconda3/envs/face/lib/python3.6/site-packages/kornia/geometry/transform/imgwarp.py", line 192, in warp_affine
    dst_norm_trans_src_norm: torch.Tensor = normalize_homography(M_3x3, (H, W), dsize)
  File "/data/data_gjx/anaconda3/envs/face/lib/python3.6/site-packages/kornia/geometry/transform/homography_warper.py", line 380, in normalize_homography
    src_pix_trans_src_norm = _torch_inverse_cast(src_norm_trans_src_pix)
  File "/data/data_gjx/anaconda3/envs/face/lib/python3.6/site-packages/kornia/utils/helpers.py", line 48, in _torch_inverse_cast
    return torch.inverse(input.to(dtype)).to(input.dtype)
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

**Comment by syysummer** [comment]
> Traceback (most recent call last): File "train.py", line 177, in main(0, world_size, train_opt) File "train.py", line 87, in main model.optimize_parameters() # calculate loss functions, get gradients, update network weights File "/data1/data_gjx/train/face/Deep3DFaceRecon_pytorch/models/facerecon_model.py", line 185, in optimize_parameters self.compute_losses() File "/data1/data_gjx/train/face/Deep3DFaceRecon_pytorch/models/facerecon_model.py", line 155, in compute_losses pred_feat = self.net_recog(self.pred_face, trans_m) File "/data/data_gjx/anaconda3/envs/face/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl return forward_call(*input, **kwargs) File "/data1/data_gjx/train/face/Deep3DFaceRecon_pytorch/models/networks.py", line 122, in forward image = self.preprocess(resize_n_crop(image, M, self.input_size)) File "/data1/data_gjx/train/face/Deep3DFaceRecon_pytorch/models/networks.py", line 24, in resize_n_crop return warp_affine(image, M, dsize=(dsize, dsize)) File "/data/data_gjx/anaconda3/envs/face/lib/python3.6/site-packages/kornia/geometry/transform/imgwarp.py", line 192, in warp_affine dst_norm_trans_src_norm: torch.Tensor = normalize_homography(M_3x3, (H, W), dsize) File "/data/data_gjx/anaconda3/envs/face/lib/python3.6/site-packages/kornia/geometry/transform/homography_warper.py", line 380, in normalize_homography src_pix_trans_src_norm = _torch_inverse_cast(src_norm_trans_src_pix) File "/data/data_gjx/anaconda3/envs/face/lib/python3.6/site-packages/kornia/utils/helpers.py", line 48, in _torch_inverse_cast return torch.inverse(input.to(dtype)).to(input.dtype) RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

I encountered the same problem as you, did you solve it?
