### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by AndreyRGW** [sicxu/Deep3DFaceRecon_pytorch#175]
```
(deep3d_pytorch) F:\WBC\Deep3DFaceRecon_pytorch>python test.py --name=model --epoch=20 --img_folder=./input
C:\ProgramData\anaconda3\envs\deep3d_pytorch\lib\site-packages\kornia\augmentation\augmentation.py:1875: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
C:\ProgramData\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
----------------- Options ---------------
                add_image: True
               bfm_folder: BFM
                bfm_model: BFM_model_front.mat
                 camera_d: 10.0
                   center: 112.0
          checkpoints_dir: ./checkpoints
             dataset_mode: None
                 ddp_port: 12355
        display_per_batch: True
                    epoch: 20                                   [default: latest]
          eval_batch_nums: inf
                    focal: 1015.0
                  gpu_ids: 0
               img_folder: ./input                              [default: examples]
                init_path: checkpoints/init_model/resnet50-0676ba61.pth
                  isTrain: False                                [default: None]
                    model: facerecon
                     name: model                                [default: face_recon]
                net_recon: resnet50
                    phase: test
                   suffix:
                  use_ddp: False                                [default: True]
              use_last_fc: False
               use_opengl: True
                  verbose: False
           vis_batch_nums: 1
               world_size: 1
                    z_far: 15.0
                   z_near: 5.0
----------------- End -------------------
model [FaceReconModel] was created
loading the model from ./checkpoints\model\epoch_20.pth
0 ./input\t3.jpg
C:\ProgramData\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0x8e in position 0: invalid start byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Traceback (most recent call last):
  File "test.py", line 73, in <module>
    main(0, opt,opt.img_folder)
  File "test.py", line 63, in main
    model.test()           # run inference
  File "F:\WBC\Deep3DFaceRecon_pytorch\models\base_model.py", line 162, in test
    self.forward()
  File "F:\WBC\Deep3DFaceRecon_pytorch\models\facerecon_model.py", line 140, in forward
    self.pred_vertex, self.facemodel.face_buf, feat=self.pred_color)
  File "C:\ProgramData\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "F:\WBC\Deep3DFaceRecon_pytorch\util\nvdiffrast.py", line 61, in forward
    self.ctx = dr.RasterizeGLContext(device=device)
  File "C:\ProgramData\anaconda3\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "C:\ProgramData\anaconda3\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "C:\ProgramData\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 974, in load
    keep_intermediates=keep_intermediates)
  File "C:\ProgramData\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1190, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\ProgramData\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1538, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "C:\ProgramData\anaconda3\envs\deep3d_pytorch\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\ProgramData\anaconda3\envs\deep3d_pytorch\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by Aurelyano** [comment]
hi, have you solved the problem? I got the same error after i installed cuda

**Comment by AndreyRGW** [comment]
> hi, have you solved the problem? I got the same error after i installed cuda

Yes I was able to solve this problem, I had to install cuda 10.2 toolkit
