### ISSUE TITLE
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': ninja: error: build.ninja:3: lexing error

### ISSUE THREAD

**Issue by cjkangme** [sicxu/Deep3DFaceRecon_pytorch#176]
Hi, I am facing an issue with nvduffrast.

Yesterday when I ran it for the first time it worked fine, but after restarting my computer, when I run it I get the following error.

```
Traceback (most recent call last):
  File "C:\Users\changjin_kang\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1723, in _run_ninja_build
    env=env)
  File "C:\Users\changjin_kang\anaconda3\envs\deep3d_pytorch\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 73, in <module>
    main(0, opt,opt.img_folder)
  File "test.py", line 63, in main
    model.test()           # run inference
  File "C:\Users\changjin_kang\Desktop\ai\Deep3DFaceRecon_pytorch\models\base_model.py", line 162, in test
    self.forward()
  File "C:\Users\changjin_kang\Desktop\ai\Deep3DFaceRecon_pytorch\models\facerecon_model.py", line 140, in forward
    self.pred_vertex, self.facemodel.face_buf, feat=self.pred_color)
  File "C:\Users\changjin_kang\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\changjin_kang\Desktop\ai\Deep3DFaceRecon_pytorch\util\nvdiffrast.py", line 61, in forward
    self.ctx = dr.RasterizeGLContext(device=device)
  File "C:\Users\changjin_kang\anaconda3\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "C:\Users\changjin_kang\anaconda3\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "C:\Users\changjin_kang\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1136, in load
    keep_intermediates=keep_intermediates)
  File "C:\Users\changjin_kang\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1347, in _jit_compile
    is_standalone=is_standalone)
  File "C:\Users\changjin_kang\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1452, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "C:\Users\changjin_kang\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': ninja: error: build.ninja:3: lexing error
```

I tried changing the RasterizeGLContext in `./util/nvdiffrast.py` to RasterizeCudaContext as advised by the internet, but I get the same error, only the error message is changed to `RuntimeError: Error building extension 'nvdiffrast_plugin'`.

Here's my setup
```
Python 3.6.15
ninja 1.11.1.git.kitware.jobserver-1
cuda_12.1.r12.1
pytorch '1.10.2'
'NVIDIA GeForce RTX 4060 Ti' (`torch.cuda.get_device_name(0)`)
```

**Comment by cjkangme** [comment]
I fixed this issue after installing libegl1-mesa-dev.
Ubuntu 22.04

`sudo apt-get install libegl1-mesa-dev `

**Comment by WiseCodeArtist** [comment]
If windows，how to fix？
