### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by MeenakshyAMenon** [sicxu/Deep3DFaceRecon_pytorch#178]
(deep3d_pytorch) C:\Users\User\Deep3DFaceRecon_pytorch>python test.py --name=model --epoch=20 --img_folder=testimage
----------------- Options ---------------
                add_image: True
               bfm_folder: BFM
                bfm_model: BFM_model_front.mat
                 camera_d: 10.0
                   center: 112.0
          checkpoints_dir: ./checkpoints
             dataset_mode: None
                 ddp_port: 12355
        display_per_batch: True
                    epoch: 20                                   [default: latest]
          eval_batch_nums: inf
                    focal: 1015.0
                  gpu_ids: 0
               img_folder: testimage                            [default: examples]
                init_path: checkpoints/init_model/resnet50-0676ba61.pth
                  isTrain: False                                [default: None]
                    model: facerecon
                     name: model                                [default: face_recon]
                net_recon: resnet50
                    phase: test
                   suffix:
                  use_ddp: False                                [default: True]
              use_last_fc: False
               use_opengl: True
                  verbose: False
           vis_batch_nums: 1
               world_size: 1
                    z_far: 15.0
                   z_near: 5.0
----------------- End -------------------
model [FaceReconModel] was created
loading the model from ./checkpoints\model\epoch_20.pth
0 testimage\000002.jpg
Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1723, in _run_ninja_build
    env=env)
  File "C:\Users\User\.conda\envs\deep3d_pytorch\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 73, in <module>
    main(0, opt,opt.img_folder)
  File "test.py", line 63, in main
    model.test()           # run inference
  File "C:\Users\User\Deep3DFaceRecon_pytorch\models\base_model.py", line 162, in test
    self.forward()
  File "C:\Users\User\Deep3DFaceRecon_pytorch\models\facerecon_model.py", line 140, in forward
    self.pred_vertex, self.facemodel.face_buf, feat=self.pred_color)
  File "C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\User\Deep3DFaceRecon_pytorch\util\nvdiffrast.py", line 61, in forward
    self.ctx = dr.RasterizeGLContext(device=device)
  File "C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1136, in load
    keep_intermediates=keep_intermediates)
  File "C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1347, in _jit_compile
    is_standalone=is_standalone)
  File "C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1452, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/6] cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\TH -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -IC:\Users\User\.conda\envs\deep3d_pytorch\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DNVDR_TORCH -c C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\common\rasterize_gl.cpp /Forasterize_gl.o
FAILED: rasterize_gl.o
cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\TH -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -IC:\Users\User\.conda\envs\deep3d_pytorch\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DNVDR_TORCH -c C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\common\rasterize_gl.cpp /Forasterize_gl.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33520 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\cstddef(11): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
[2/6] cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\TH -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -IC:\Users\User\.conda\envs\deep3d_pytorch\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DNVDR_TORCH -c C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\torch_rasterize_gl.cpp /Fotorch_rasterize_gl.o
FAILED: torch_rasterize_gl.o
cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\TH -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -IC:\Users\User\.conda\envs\deep3d_pytorch\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DNVDR_TORCH -c C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\torch_rasterize_gl.cpp /Fotorch_rasterize_gl.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33520 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\cstddef(11): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
[3/6] cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\TH -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -IC:\Users\User\.conda\envs\deep3d_pytorch\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DNVDR_TORCH -c C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\torch_bindings_gl.cpp /Fotorch_bindings_gl.o
FAILED: torch_bindings_gl.o
cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\TH -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -IC:\Users\User\.conda\envs\deep3d_pytorch\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DNVDR_TORCH -c C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\torch_bindings_gl.cpp /Fotorch_bindings_gl.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33520 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\cstddef(11): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
[4/6] cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\TH -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -IC:\Users\User\.conda\envs\deep3d_pytorch\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DNVDR_TORCH -c C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\common\common.cpp /Focommon.o
FAILED: common.o
cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\TH -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -IC:\Users\User\.conda\envs\deep3d_pytorch\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DNVDR_TORCH -c C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\common\common.cpp /Focommon.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33520 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include\driver_types.h(80): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
[5/6] cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\TH -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -IC:\Users\User\.conda\envs\deep3d_pytorch\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DNVDR_TORCH -c C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\common\glutil.cpp /Foglutil.o
FAILED: glutil.o
cl /showIncludes -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\TH -IC:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include" -IC:\Users\User\.conda\envs\deep3d_pytorch\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -DNVDR_TORCH -c C:\Users\User\.conda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\common\glutil.cpp /Foglutil.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33520 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\cstddef(11): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
ninja: build stopped: subcommand failed.

this is so much emergency for me.somebody please help

**Comment by FORRYKIM** [comment]
same problems，have you ever solved? thank you

**Comment by ghweaiudr** [comment]
i want konw hou to solve it.
