### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 1454: invalid continuation byte

### ISSUE THREAD

**Issue by 1748378211** [sicxu/Deep3DFaceRecon_pytorch#179]
Traceback (most recent call last):
  File "test.py", line 72, in <module>
    main(0, opt,opt.img_folder)
  File "test.py", line 62, in main
    model.test()           # run inference
  File "D:\Deep3DFaceRecon_pytorch\Deep3DFaceRecon_pytorch\models\base_model.py", line 162, in test
    self.forward()
  File "D:\Deep3DFaceRecon_pytorch\Deep3DFaceRecon_pytorch\models\facerecon_model.py", line 139, in forward
    self.pred_vertex, self.facemodel.face_buf, feat=self.pred_color)
  File "D:\Anaconda\envs\deep3d_pytorch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Deep3DFaceRecon_pytorch\Deep3DFaceRecon_pytorch\util\nvdiffrast.py", line 58, in forward
    self.glctx = dr.RasterizeGLContext(device=device)
  File "D:\Anaconda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "D:\Anaconda\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "D:\Anaconda\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "D:\Anaconda\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1302, in _jit_compile
    is_standalone=is_standalone)
  File "D:\Anaconda\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1407, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "D:\Anaconda\envs\deep3d_pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
    message += f": {error.output.decode()}"  # type: ignore
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 1454: invalid continuation byte

**Comment by Wayne451-b** [comment]
I have the same question!
