### ISSUE TITLE
ImportError: libtorch_cpu.so: undefined symbol: iJIT_IsProfilingActive

### ISSUE THREAD

**Issue by Megidd** [sicxu/Deep3DFaceRecon_pytorch#180]
I'm getting the same error on my local machine and also on Google Colab:

```bash
(deep3d_pytorch) m3@i7:~/repos/Deep3DFaceRecon_pytorch> python test.py --name=facerecon_20230425 --epoch=20 --img_folder=custom_images
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from options.test_options import TestOptions
  File "/home/m3/repos/Deep3DFaceRecon_pytorch/options/test_options.py", line 4, in <module>
    from .base_options import BaseOptions
  File "/home/m3/repos/Deep3DFaceRecon_pytorch/options/base_options.py", line 6, in <module>
    from util import util
  File "/home/m3/repos/Deep3DFaceRecon_pytorch/util/util.py", line 5, in <module>
    import torch
  File "/home/m3/anaconda3/envs/deep3d_pytorch/lib/python3.6/site-packages/torch/__init__.py", line 189, in <module>
    from torch._C import *
ImportError: /home/m3/anaconda3/envs/deep3d_pytorch/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_IsProfilingActive
```

Screenshots:

![Screenshot_20240414_155409](https://github.com/sicxu/Deep3DFaceRecon_pytorch/assets/17475482/a8238881-e0cb-45fa-8fa4-a6255f1e3297)

![Screenshot_20240414_154408](https://github.com/sicxu/Deep3DFaceRecon_pytorch/assets/17475482/b300aa11-6142-4cb6-a5e9-10ea8fc64926)

**Comment by Megidd** [comment]
Looks like this is the underlying problem, I have explained: https://stackoverflow.com/q/78326712/3405291

**Comment by Megidd** [comment]
Even a simple statement to get the PyTorch version throws the error:

```bash
(deep3d_pytorch) m3@i7:~/repos/Deep3DFaceRecon_pytorch> python -c "import torch; print(torch.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/m3/anaconda3/envs/deep3d_pytorch/lib/python3.6/site-packages/torch/__init__.py", line 189, in <module>
    from torch._C import *
ImportError: /home/m3/anaconda3/envs/deep3d_pytorch/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_IsProfilingActive
```

On both local machine and Google Colab:

![Screenshot_20240415_153919](https://github.com/sicxu/Deep3DFaceRecon_pytorch/assets/17475482/592b7e1a-ae70-4675-92fe-a8ba8ea78f64)

![Screenshot_20240415_154305](https://github.com/sicxu/Deep3DFaceRecon_pytorch/assets/17475482/029a8e79-93b1-428f-8375-a4d1adb9cf50)

# Implication

Does it mean the PyTorch installation by Conda is broken?

**Comment by Megidd** [comment]
The error was resolved by just removing all the versions from the `environment.yml` file. There were problems with the versions and mismatches between them like this one:

https://discuss.pytorch.org/t/libtorch-cpu-so-undefined-symbol/201101/2?u=megidd

Final `environment.yml` file: 

```yml
name: deep3d_pytorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch
  - torchvision
  - numpy
  - scikit-image
  - scipy
  - pillow
  - pip
  - ipython
  - yaml
  - pip:
    - matplotlib
    - opencv-python
    - tensorboard
    - tensorflow
    - kornia
    - dominate
    - trimesh

```

**Comment by Megidd** [comment]
# Google Colab

Our final approach on Google Colab that works just fine is:

```bash
# Step 1: Press runtime on the top > Change runtime type > Select T4 GPU

# Step 2: Run this shell

!wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
!bash miniconda.sh -b -u -p /usr/local
!rm miniconda.sh
!conda update conda

%cd /content/
!rm -rf Deep3DFaceRecon_pytorch
!git clone https://github.com/sicxu/Deep3DFaceRecon_pytorch.git
%cd Deep3DFaceRecon_pytorch
!git clone https://github.com/NVlabs/nvdiffrast
!git clone https://github.com/deepinsight/insightface.git
!cp -r ./insightface/recognition/arcface_torch ./models/

# Step 3: Mount drive and copy the files mounted in google drive:

!mkdir /content/Deep3DFaceRecon_pytorch/checkpoints
!cp -r /content/drive/MyDrive/Deep3D/facerecon_20230425 /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425
!cp /content/drive/MyDrive/Deep3D/01_MorphableModel.mat /content/Deep3DFaceRecon_pytorch/BFM/
!cp /content/drive/MyDrive/Deep3D/Exp_Pca.bin /content/Deep3DFaceRecon_pytorch/BFM/

# Step 4: Install the graphics related stuff

!sudo apt-get install libegl1-mesa-dev
!nvidia-smi
!sudo apt-get install libnvidia-gl-535

# Step 5: Run this shell to install everything

%%shell
eval "$(conda shell.bash hook)"
conda create --name deep3d_pytorch python=3.6 -y
conda activate deep3d_pytorch
conda config --env --add channels pytorch
conda config --env --add channels conda-forge
conda config --env --add channels defaults
conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.2 -c pytorch -y
conda install numpy scikit-image=0.16.2 scipy=1.4.1 pillow=6.2.1 pip ipython=7.13.0 yaml=0.1.7 -y
pip install matplotlib==2.2.5 opencv-python==3.4.9.33 tensorboard==1.15.0 tensorflow==1.15.0 kornia==0.5.5 dominate==2.6.0 trimesh==3.9.20
pip install ./nvdiffrast/.

# Step 6: Run this shell to test the program

%%shell
eval "$(conda shell.bash hook)"
conda activate deep3d_pytorch
python test.py --name=facerecon_20230425 --epoch=20 --img_folder=./datasets/examples

# Step 7: Copy test results to Google Drive

!ls /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/examples/epoch_20_000000/
!cp /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/examples/epoch_20_000000/* /content/drive/MyDrive/Deep3D/results/

# Step 8: prepare custom images along with their facial landmarks

!cp -r /content/drive/MyDrive/Deep3D/custom_images /content/Deep3DFaceRecon_pytorch/
%cd /content/Deep3DFaceRecon_pytorch/custom_images/
!python -m venv virtual_env
!source virtual_env/bin/activate && which pip
!source virtual_env/bin/activate && pip install mtcnn
!source virtual_env/bin/activate && pip install tensorflow
!source virtual_env/bin/activate && which python
!source virtual_env/bin/activate && python facial_landmarks.py # This Python script source code can be found here: https://github.com/sicxu/Deep3DFaceRecon_pytorch/issues/85#issuecomment-2069302718
%cd /content/Deep3DFaceRecon_pytorch/

# Step 9: run with custom images

%%shell
eval "$(conda shell.bash hook)"
conda activate deep3d_pytorch
python test.py --name=facerecon_20230425 --epoch=20 --img_folder=./custom_images

# Step 10: copy the results back to Google Drive

!ls /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/custom_images/epoch_20_000000/
!cp /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/custom_images/epoch_20_000000/* /content/drive/MyDrive/Deep3D/results/
```
