### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'BFM/01_MorphableModel.mat'

### ISSUE THREAD

**Issue by loretoparisi** [sicxu/Deep3DFaceRecon_pytorch#39]
When trying to run the examples

```
! python test.py --name=my_model--epoch=20 --img_folder=./datasets/examples
```

Full stack trace

```
Traceback (most recent call last):
  File "test.py", line 72, in <module>
    main(0, opt,opt.img_folder)
  File "test.py", line 41, in main
    model = create_model(opt)
  File "/content/Deep3DFaceRecon_pytorch/models/__init__.py", line 65, in create_model
    instance = model(opt)
  File "/content/Deep3DFaceRecon_pytorch/models/facerecon_model.py", line 95, in __init__
    is_train=self.isTrain, default_name=opt.bfm_model
  File "/content/Deep3DFaceRecon_pytorch/models/bfm.py", line 40, in __init__
    transferBFM09(bfm_folder)
  File "/content/Deep3DFaceRecon_pytorch/util/load_mats.py", line 34, in transferBFM09
    original_BFM = loadmat(osp.join(bfm_folder, '01_MorphableModel.mat'))
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 216, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 19, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'BFM/01_MorphableModel.mat'
```

I have copied files in `BFM` folder and model to `checkpoints` folders:

<img width="245" alt="Schermata 2021-11-14 alle 18 21 10" src="https://user-images.githubusercontent.com/163333/141691393-4e95fa20-ed9f-4456-a8e3-b3ff164475ae.png">

**Comment by loretoparisi** [comment]
Solved downloading the file from [here](https://faces.dmi.unibas.ch/bfm/main.php?nav=1-2&id=downloads

).
