### ISSUE TITLE
OSError: could not read bytes

### ISSUE THREAD

**Issue by loretoparisi** [sicxu/Deep3DFaceRecon_pytorch#40]
After copying all [requested](https://github.com/sicxu/Deep3DFaceRecon_pytorch/issues/39) resources and running

```
# get reconstruction results of example images
! python test.py --name=my_model--epoch=20 --img_folder=./datasets/examples
```

I get this error:

```
/usr/local/lib/python3.7/dist-packages/kornia/augmentation/augmentation.py:1875: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
----------------- Options ---------------
                add_image: True                          
               bfm_folder: BFM                           
                bfm_model: BFM_model_front.mat           
                 camera_d: 10.0                          
                   center: 112.0                         
          checkpoints_dir: ./checkpoints                 
             dataset_mode: None                          
                 ddp_port: 12355                         
        display_per_batch: True                          
                    epoch: latest                        
          eval_batch_nums: inf                           
                    focal: 1015.0                        
                  gpu_ids: 0                             
               img_folder: ./datasets/examples           	[default: examples]
                init_path: checkpoints/init_model/resnet50-0676ba61.pth
                  isTrain: False                         	[default: None]
                    model: facerecon                     
                     name: my_model--epoch=20            	[default: face_recon]
                net_recon: resnet50                      
                    phase: test                          
                   suffix:                               
                  use_ddp: False                         	[default: True]
              use_last_fc: False                         
                  verbose: False                         
           vis_batch_nums: 1                             
               world_size: 1                             
                    z_far: 15.0                          
                   z_near: 5.0                           
----------------- End -------------------
Transfer BFM09 to BFM_model_front......
Traceback (most recent call last):
  File "test.py", line 72, in <module>
    main(0, opt,opt.img_folder)
  File "test.py", line 41, in main
    model = create_model(opt)
  File "/content/Deep3DFaceRecon_pytorch/models/__init__.py", line 65, in create_model
    instance = model(opt)
  File "/content/Deep3DFaceRecon_pytorch/models/facerecon_model.py", line 95, in __init__
    is_train=self.isTrain, default_name=opt.bfm_model
  File "/content/Deep3DFaceRecon_pytorch/models/bfm.py", line 40, in __init__
    transferBFM09(bfm_folder)
  File "/content/Deep3DFaceRecon_pytorch/util/load_mats.py", line 34, in transferBFM09
    original_BFM = loadmat(osp.join(bfm_folder, '01_MorphableModel.mat'))
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 218, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 703, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 777, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex
  File "mio5_utils.pyx", line 450, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric
  File "mio5_utils.pyx", line 355, in scipy.io.matlab.mio5_utils.VarReader5.read_element
  File "streams.pyx", line 200, in scipy.io.matlab.streams.ZlibInputStream.read_string
  File "streams.pyx", line 193, in scipy.io.matlab.streams.ZlibInputStream.read_into
OSError: could not read bytes
```

**Comment by sicxu** [comment]
You may double check the integrity or path of your "01_MorphableModel.mat".
