### ISSUE TITLE
RuntimeError: invalid argument 7: equal number of batches expected at /opt/conda/conda-bld/pytorch_1603729128610/work/aten/src/THC/generic/THCTensorMathBlas.cu:32

### ISSUE THREAD

**Issue by VictoryLoveJessica** [sicxu/Deep3DFaceRecon_pytorch#72]
Thanks for your great code!

But I encountered this problem when I ran the training code：
————————————————————————————————————————————
Traceback (most recent call last):
  File "train.py", line 164, in <module>
    mp.spawn(main, args=(world_size, train_opt), nprocs=world_size, join=True)
  File "/home/zhangtianke/anaconda3/envs/deep3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/zhangtianke/anaconda3/envs/deep3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/zhangtianke/anaconda3/envs/deep3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/zhangtianke/anaconda3/envs/deep3d/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/zhangtianke/Deep3DFaceRecon_pytorch-master/train.py", line 79, in main
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/home/zhangtianke/Deep3DFaceRecon_pytorch-master/models/facerecon_model.py", line 178, in optimize_parameters
    self.compute_losses()
  File "/home/zhangtianke/Deep3DFaceRecon_pytorch-master/models/facerecon_model.py", line 152, in compute_losses
    pred_feat = self.net_recog(self.pred_face, trans_m)
  File "/home/zhangtianke/anaconda3/envs/deep3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhangtianke/Deep3DFaceRecon_pytorch-master/models/networks.py", line 122, in forward
    image = self.preprocess(resize_n_crop(image, M, self.input_size))
  File "/home/zhangtianke/Deep3DFaceRecon_pytorch-master/models/networks.py", line 24, in resize_n_crop
    return warp_affine(image, M, dsize=(dsize, dsize))
  File "/home/zhangtianke/anaconda3/envs/deep3d/lib/python3.6/site-packages/kornia/geometry/transform/imgwarp.py", line 197, in warp_affine
    grid = F.affine_grid(src_norm_trans_dst_norm[:, :2, :], [B, C, dsize[0], dsize[1]], align_corners=align_corners)
  File "/home/zhangtianke/anaconda3/envs/deep3d/lib/python3.6/site-packages/torch/nn/functional.py", line 3483, in affine_grid
    return torch.affine_grid_generator(theta, size, align_corners)
RuntimeError: invalid argument 7: equal number of batches expected at /opt/conda/conda-bld/pytorch_1603729128610/work/aten/src/THC/generic/THCTensorMathBlas.cu:32

**Comment by VictoryLoveJessica** [comment]
According to #26 , my batch number of validation images is normal:
model [FaceReconModel] was created
model [FaceReconModel] was created
The batch number of training images = 1875
,             the batch number of validation images = 312
---------- Networks initialized -------------
[Network net_recon] Total number of parameters : 24.035 M

**Comment by VictoryLoveJessica** [comment]
I solved it with the correct nvidraffst

**Comment by want2333** [comment]
> I solved it with the correct nvidraffst
Hello I have the same problem. What does the “correct nvidraffst” mean?

**Comment by VictoryLoveJessica** [comment]
Hello, that means I did not install nvidraffst with the correct step before.
You may try it again:
cd nvdiffrast    # ./Deep3DFaceRecon_pytorch/nvdiffrast
pip install .
