### ISSUE TITLE
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Bruce-ywj** [sicxu/Deep3DFaceRecon_pytorch#78]
2022-04-26 10:53:11.630608: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
Traceback (most recent call last):
  File "/data/ywj/Anaconda3/envs/torch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-0e47f5b4e6b6>", line 4, in <module>
    runfile('/data/ywj/Code-of-original/Sequence-to-function/LM_model.py', wdir='/data/ywj/Code-of-original/Sequence-to-function')
  File "/home/ywj/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/ywj/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/data/ywj/Code-of-original/Sequence-to-function/LM_model.py", line 308, in <module>
    wd = wd)
  File "/data/ywj/Code-of-original/Sequence-to-function/NuSpeak_base.py", line 499, in NuSpeak_learner
    drop_mult = drop_mult
  File "/data/ywj/Code-of-original/Sequence-to-function/NuSpeak_base.py", line 472, in get_NuSpeak_model
    encoder = arch(vocab_sz, **config)
  File "/data/ywj/Anaconda3/envs/torch/lib/python3.6/site-packages/fastai/core.py", line 66, in _init
    old_init(self, *args,**kwargs)
  File "/data/ywj/Anaconda3/envs/torch/lib/python3.6/site-packages/fastai/text/models/awd_lstm.py", line 95, in __init__
    from .qrnn import QRNN
  File "/data/ywj/Anaconda3/envs/torch/lib/python3.6/site-packages/fastai/text/models/qrnn.py", line 11, in <module>
    forget_mult_cuda = load(name='forget_mult_cuda', sources=[fastai_path/f for f in files])
  File "/data/ywj/Anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 980, in load
    keep_intermediates=keep_intermediates)
  File "/data/ywj/Anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1185, in _jit_compile
    with_cuda=with_cuda)
  File "/data/ywj/Anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1256, in _write_ninja_file_and_build_library
    check_compiler_abi_compatibility(compiler)
  File "/data/ywj/Anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 252, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/data/ywj/Anaconda3/envs/torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 212, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/data/ywj/Anaconda3/envs/torch/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/data/ywj/Anaconda3/envs/torch/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.
Process finished with exit code 0

I have installed gcc/g++7.3.0 (non-root) in  /data/ywj/gcc73/gcc73
But when I connect to the server remotely and run the program in pycharm, I get this error 
Please help

**Comment by liuyongjie985** [comment]
me too have you solved this problem？

**Comment by etranger7** [comment]
Installing build essentials that includes g++ solved this problem for me
~~~
sudo apt install build-essential
~~~
